project:
  type: website

website:
  title: "CJ Mendes"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/candidobrau
      - icon: twitter
        href: https://twitter.com/candidobrau
      - icon: linkedin
        href: https://www.linkedin.com/in/candidomendes/
format:
  html:
    theme: flatly
    css: styles.css



